### ISSUE TITLE
Not working for Unity 2018.2.18 build

### ISSUE THREAD

**Issue by baroquedub** [Eusth/VRGIN.Template#10]
I'm guessing this is related to issue [https://github.com/Eusth/VRGIN.Template/issues/7](https://github.com/Eusth/VRGIN.Template/issues/7)?

Getting the following error:
```
Patching UnityEngine.dll... ERROR: Oops! This should not have happened.

System.Exception: Could not find any entry type!
   at IPA.Patcher.PatchedModule.Patch()
   at IPA.Program.Install(PatchContext context)
```

What's the known working Unity version?

**Comment by renxida** [comment]
Same problem, 2018.4.12 build, game is Dyson Sphere Program.
